import { Metadata } from "next";
import { FC } from "react";

interface pageProps {}

// if you use meta data in page file, there were declared here and said only in the profile page, not there subsequent routes in the profile
export const metadata: Metadata = {
  title: "Profile - NextJs App Router Example",
  description: "Generated by create next app",
};

const page: FC<pageProps> = async ({}) => {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts/1", {
    method: "GET",
  });
  const data = await response.json();

  return (
    <>
      <div>Profile Page</div>
      <h2>{JSON.stringify(data)}</h2>
    </>
  );
};

export default page;
