import { Metadata } from "next";
import { FC, ReactNode } from "react";

interface layoutProps {
  children: ReactNode;
}

// if you use metadata in the layout file, there were any subsequent routes in the dashboard
// http://localhost:3000/dashboard
// http://localhost:3000/dashboard/address
export const metadata: Metadata = {
  title: "Dashboard - NextJs App Router Example",
  description: "Generated by create next app",
};

const layout: FC<layoutProps> = ({ children }) => {
  return <div className=''>{children}</div>;
};

export default layout;
